apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: japan-webui-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: japan-webui
    k8s.kuboard.cn/workload: japan-webui
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure

spec:
  rules:
    - host: www.npool.top
      http:
        paths:
          - path: /
            backend:
              serviceName: japan-webui
              servicePort: 80
