export default function () {
  return {
    goods: {
      Details: [
        {
          ID: '',
          DeviceInfo: {
            ID: '',
            Type: '',
            Manufacturer: '',
            PowerComsuption: 0,
            ShipmentAt: 0,
          },
          SeparateFee: true,
          UnitPower: 0,
          DurationDays: 0,
          CoinInfo: {
            ID: '',
            PreSale: true,
            Name: '',
            Unit: '',
            Logo: '',
          },
          Actuals: true,
          DeliveryAt: 0,
          InheritFromGood: {
            ID: '',
            DeviceInfoID: '',
            SeparateFee: true,
            UnitPower: 0,
            DurationDays: 0,
            CoinInfoID: '',
            Actuals: true,
            DeliveryAt: 0,
            InheritFromGoodID: '',
            VendorLocationID: '',
            Price: 0,
            BenefitType: '',
            Classic: true,
            SupportCoinTypeIDs: [],
            Total: 0,
            PriceCurrency: '',
            Title: '',
            Unit: '',
            Start: 0,
          },
          VendorLocation: {
            ID: '',
            Country: '',
            Province: '',
            City: '',
            Address: '',
          },
          Price: 0,
          BenefitType: '',
          Classic: true,
          SupportCoins: [
            {
              ID: '',
              PreSale: true,
              Name: '',
              Unit: '',
              Logo: '',
            },
          ],
          Total: 0,
          Extra: {
            ID: '',
            GoodID: '',
            Posters: [],
            Labels: [],
            OutSale: true,
            PreSale: true,
            VoteCount: 0,
            Rating: 0,
          },
          Title: '',
          Unit: '',
          Start: 0,
          PriceCurrency: {
            ID: '',
            Name: '',
            Unit: '',
            Symbol: '',
          },
          Fees: [
            {
              Fee: {
                ID: '',
                AppID: '',
                FeeType: '',
                FeeDescription: '',
                PayType: '',
              },
              Value: 0,
            },
          ],
        },
      ],
      Total: 0,
    },
  };
}
