export const countries = [
  {
    name: "Andorra",
    chinese_name: "安道尔",
    country_code: "AD",
    label: "+376",
  },
  {
    name: "United Arab Emirates",
    chinese_name: "阿拉伯联合酋长国",
    country_code: "AE",
    label: "+971",
  },
  {
    name: "Afghanistan",
    chinese_name: "阿富汗",
    country_code: "AF",
    label: "+93",
  },
  {
    name: "Antigua and Barbuda",
    chinese_name: "安提瓜和巴布达",
    country_code: "AG",
    label: "+1268",
  },
  {
    name: "Anguilla",
    chinese_name: "安圭拉",
    country_code: "AI",
    label: "+1264",
  },
  {
    name: "Albania",
    chinese_name: "阿尔巴尼亚",
    country_code: "AL",
    label: "+355",
  },
  {
    name: "Armenia",
    chinese_name: "亚美尼亚",
    country_code: "AM",
    label: "+374",
  },
  {
    name: "Angola",
    chinese_name: "安哥拉",
    country_code: "AO",
    label: "+244",
  },
  {
    name: "Argentina",
    chinese_name: "阿根廷",
    country_code: "AR",
    label: "+54",
  },
  {
    name: "American Samoa",
    chinese_name: "美属萨摩亚",
    country_code: "AS",
    label: "+1684",
  },
  {
    name: "Austria",
    chinese_name: "奥地利",
    country_code: "AT",
    label: "+43",
  },
  {
    name: "Australia",
    chinese_name: "澳大利亚",
    country_code: "AU",
    label: "+61",
  },
  {
    name: "Aruba",
    chinese_name: "阿鲁巴",
    country_code: "AW",
    label: "+297",
  },
  {
    name: "Azerbaijan",
    chinese_name: "阿塞拜疆",
    country_code: "AZ",
    label: "+994",
  },
  {
    name: "Bosniaand Herzegovina",
    chinese_name: "波斯尼亚和黑塞哥维那",
    country_code: "BA",
    label: "+387",
  },
  {
    name: "Barbados",
    chinese_name: "巴巴多斯",
    country_code: "BB",
    label: "+1246",
  },
  {
    name: "Bangladesh",
    chinese_name: "孟加拉国",
    country_code: "BD",
    label: "+880",
  },
  {
    name: "Belgium",
    chinese_name: "比利时",
    country_code: "BE",
    label: "+32",
  },
  {
    name: "Burkina Faso",
    chinese_name: "布基纳法索",
    country_code: "BF",
    label: "+226",
  },
  {
    name: "Bulgaria",
    chinese_name: "保加利亚",
    country_code: "BG",
    label: "+359",
  },
  {
    name: "Bahrain",
    chinese_name: "巴林",
    country_code: "BH",
    label: "+973",
  },
  {
    name: "Burundi",
    chinese_name: "布隆迪",
    country_code: "BI",
    label: "+257",
  },
  {
    name: "Benin",
    chinese_name: "贝宁",
    country_code: "BJ",
    label: "+229",
  },
  {
    name: "Bermuda",
    chinese_name: "百慕大群岛",
    country_code: "BM",
    label: "+1441",
  },
  {
    name: "Brunei",
    chinese_name: "文莱",
    country_code: "BN",
    label: "+673",
  },
  {
    name: "Bolivia",
    chinese_name: "玻利维亚",
    country_code: "BO",
    label: "+591",
  },
  {
    name: "Caribisch Nederland",
    chinese_name: "荷兰加勒比",
    country_code: "BQ",
    label: "+599",
  },
  {
    name: "Brazil",
    chinese_name: "巴西",
    country_code: "BR",
    label: "+55",
  },
  {
    name: "Bahamas",
    chinese_name: "巴哈马",
    country_code: "BS",
    label: "+1242",
  },
  {
    name: "Bhutan",
    chinese_name: "不丹",
    country_code: "BT",
    label: "+975",
  },
  {
    name: "Botswana",
    chinese_name: "博茨瓦纳",
    country_code: "BW",
    label: "+267",
  },
  {
    name: "Belarus",
    chinese_name: "白俄罗斯",
    country_code: "BY",
    label: "+375",
  },
  {
    name: "Belize",
    chinese_name: "伯利兹",
    country_code: "BZ",
    label: "+501",
  },
  {
    name: "Canada",
    chinese_name: "加拿大",
    country_code: "CA",
    label: "+1",
  },
  {
    name: "Democratic Republic of theCongo",
    chinese_name: "刚果民主共和国",
    country_code: "CD",
    label: "+243",
  },
  {
    name: "Central African Republic",
    chinese_name: "中非共和国",
    country_code: "CF",
    label: "+236",
  },
  {
    name: "Republic Of The Congo",
    chinese_name: "刚果共和国",
    country_code: "CG",
    label: "+242",
  },
  {
    name: "Switzerland",
    chinese_name: "瑞士",
    country_code: "CH",
    label: "+41",
  },
  {
    name: "Ivory Coast",
    chinese_name: "象牙海岸",
    country_code: "CI",
    label: "+225",
  },
  {
    name: "Cook Islands",
    chinese_name: "库克群岛",
    country_code: "CK",
    label: "+682",
  },
  {
    name: "Chile",
    chinese_name: "智利",
    country_code: "CL",
    label: "+56",
  },
  {
    name: "Cameroon",
    chinese_name: "喀麦隆",
    country_code: "CM",
    label: "+237",
  },
  {
    name: "China",
    chinese_name: "中国",
    country_code: "CN",
    label: "+86",
  },
  {
    name: "Colombia",
    chinese_name: "哥伦比亚",
    country_code: "CO",
    label: "+57",
  },
  {
    name: "CostaRica",
    chinese_name: "哥斯达黎加",
    country_code: "CR",
    label: "+506",
  },
  {
    name: "Cuba",
    chinese_name: "古巴",
    country_code: "CU",
    label: "+53",
  },
  {
    name: "Cape Verde",
    chinese_name: "开普",
    country_code: "CV",
    label: "+238",
  },
  {
    name: "Curacao",
    chinese_name: "库拉索",
    country_code: "CW",
    label: "+599",
  },
  {
    name: "Cyprus",
    chinese_name: "塞浦路斯",
    country_code: "CY",
    label: "+357",
  },
  {
    name: "Czech",
    chinese_name: "捷克",
    country_code: "CZ",
    label: "+420",
  },
  {
    name: "Germany",
    chinese_name: "德国",
    country_code: "DE",
    label: "+49",
  },
  {
    name: "Djibouti",
    chinese_name: "吉布提",
    country_code: "DJ",
    label: "+253",
  },
  {
    name: "Denmark",
    chinese_name: "丹麦",
    country_code: "DK",
    label: "+45",
  },
  {
    name: "Dominica",
    chinese_name: "多米尼加",
    country_code: "DM",
    label: "+1767",
  },
  {
    name: "dominican republic",
    chinese_name: "多米尼加共和国",
    country_code: "DO",
    label: "+1809",
  },
  {
    name: "Algeria",
    chinese_name: "阿尔及利亚",
    country_code: "DZ",
    label: "+213",
  },
  {
    name: "Ecuador",
    chinese_name: "厄瓜多尔",
    country_code: "EC",
    label: "+593",
  },
  {
    name: "Estonia",
    chinese_name: "爱沙尼亚",
    country_code: "EE",
    label: "+372",
  },
  {
    name: "Egypt",
    chinese_name: "埃及",
    country_code: "EG",
    label: "+20",
  },
  {
    name: "Eritrea",
    chinese_name: "厄立特里亚",
    country_code: "ER",
    label: "+291",
  },
  {
    name: "Spain",
    chinese_name: "西班牙",
    country_code: "ES",
    label: "+34",
  },
  {
    name: "Ethiopia",
    chinese_name: "埃塞俄比亚",
    country_code: "ET",
    label: "+251",
  },
  {
    name: "Finland",
    chinese_name: "芬兰",
    country_code: "FI",
    label: "+358",
  },
  {
    name: "Fiji",
    chinese_name: "斐济",
    country_code: "FJ",
    label: "+679",
  },
  {
    name: "Micronesia",
    chinese_name: "密克罗尼西亚",
    country_code: "FM",
    label: "+691",
  },
  {
    name: "Faroe Islands",
    chinese_name: "法罗群岛",
    country_code: "FO",
    label: "+298",
  },
  {
    name: "France",
    chinese_name: "法国",
    country_code: "FR",
    label: "+33",
  },
  {
    name: "Gabon",
    chinese_name: "加蓬",
    country_code: "GA",
    label: "+241",
  },
  {
    name: "United Kingdom",
    chinese_name: "英国",
    country_code: "GB",
    label: "+44",
  },
  {
    name: "Grenada",
    chinese_name: "格林纳达",
    country_code: "GD",
    label: "+1473",
  },
  {
    name: "Georgia",
    chinese_name: "格鲁吉亚",
    country_code: "GE",
    label: "+995",
  },
  {
    name: "French Guiana",
    chinese_name: "法属圭亚那",
    country_code: "GF",
    label: "+594",
  },
  {
    name: "Ghana",
    chinese_name: "加纳",
    country_code: "GH",
    label: "+233",
  },
  {
    name: "Gibraltar",
    chinese_name: "直布罗陀",
    country_code: "GI",
    label: "+350",
  },
  {
    name: "Greenland",
    chinese_name: "格陵兰岛",
    country_code: "GL",
    label: "+299",
  },
  {
    name: "Gambia",
    chinese_name: "冈比亚",
    country_code: "GM",
    label: "+220",
  },
  {
    name: "Guinea",
    chinese_name: "几内亚",
    country_code: "GN",
    label: "+224",
  },
  {
    name: "Guadeloupe",
    chinese_name: "瓜德罗普岛",
    country_code: "GP",
    label: "+590",
  },
  {
    name: "Equatorial Guinea",
    chinese_name: "赤道几内亚",
    country_code: "GQ",
    label: "+240",
  },
  {
    name: "Greece",
    chinese_name: "希腊",
    country_code: "GR",
    label: "+30",
  },
  {
    name: "Guatemala",
    chinese_name: "瓜地马拉",
    country_code: "GT",
    label: "+502",
  },
  {
    name: "Guam",
    chinese_name: "关岛",
    country_code: "GU",
    label: "+1671",
  },
  {
    name: "Guinea-Bissau",
    chinese_name: "几内亚比绍共和国",
    country_code: "GW",
    label: "+245",
  },
  {
    name: "Guyana",
    chinese_name: "圭亚那",
    country_code: "GY",
    label: "+592",
  },
  {
    name: "Hong Kong",
    chinese_name: "中国香港",
    country_code: "HK",
    label: "+852",
  },
  {
    name: "Honduras",
    chinese_name: "洪都拉斯",
    country_code: "HN",
    label: "+504",
  },
  {
    name: "Croatia",
    chinese_name: "克罗地亚",
    country_code: "HR",
    label: "+385",
  },
  {
    name: "Haiti",
    chinese_name: "海地",
    country_code: "HT",
    label: "+509",
  },
  {
    name: "Hungary",
    chinese_name: "匈牙利",
    country_code: "HU",
    label: "+36",
  },
  {
    name: "Indonesia",
    chinese_name: "印度尼西亚",
    country_code: "ID",
    label: "+62",
  },
  {
    name: "Ireland",
    chinese_name: "爱尔兰",
    country_code: "IE",
    label: "+353",
  },
  {
    name: "Israel",
    chinese_name: "以色列",
    country_code: "IL",
    label: "+972",
  },
  {
    name: "India",
    chinese_name: "印度",
    country_code: "IN",
    label: "+91",
  },
  {
    name: "Iraq",
    chinese_name: "伊拉克",
    country_code: "IQ",
    label: "+964",
  },
  {
    name: "Iran",
    chinese_name: "伊朗",
    country_code: "IR",
    label: "+98",
  },
  {
    name: "Iceland",
    chinese_name: "冰岛",
    country_code: "IS",
    label: "+354",
  },
  {
    name: "Italy",
    chinese_name: "意大利",
    country_code: "IT",
    label: "+39",
  },
  {
    name: "Jamaica",
    chinese_name: "牙买加",
    country_code: "JM",
    label: "+1876",
  },
  {
    name: "Jordan",
    chinese_name: "约旦",
    country_code: "JO",
    label: "+962",
  },
  {
    name: "Japan",
    chinese_name: "日本",
    country_code: "JP",
    label: "+81",
  },
  {
    name: "Kenya",
    chinese_name: "肯尼亚",
    country_code: "KE",
    label: "+254",
  },
  {
    name: "Kyrgyzstan",
    chinese_name: "吉尔吉斯斯坦",
    country_code: "KG",
    label: "+996",
  },
  {
    name: "Cambodia",
    chinese_name: "柬埔寨",
    country_code: "KH",
    label: "+855",
  },
  {
    name: "Kiribati",
    chinese_name: "基里巴斯",
    country_code: "KI",
    label: "+686",
  },
  {
    name: "Comoros",
    chinese_name: "科摩罗",
    country_code: "KM",
    label: "+269",
  },
  {
    name: "Saint Kitts and Nevis",
    chinese_name: "圣基茨和尼维斯",
    country_code: "KN",
    label: "+1869",
  },
  {
    name: "Korea Democratic Rep.",
    chinese_name: "朝鲜",
    country_code: "KP",
    label: "+850",
  },
  {
    name: "South Korea",
    chinese_name: "韩国",
    country_code: "KR",
    label: "+82",
  },
  {
    name: "Kuwait",
    chinese_name: "科威特",
    country_code: "KW",
    label: "+965",
  },
  {
    name: "Cayman Islands",
    chinese_name: "开曼群岛",
    country_code: "KY",
    label: "+1345",
  },
  {
    name: "Kazakhstan",
    chinese_name: "哈萨克斯坦",
    country_code: "KZ",
    label: "+7",
  },
  {
    name: "Laos",
    chinese_name: "老挝",
    country_code: "LA",
    label: "+856",
  },
  {
    name: "Lebanon",
    chinese_name: "黎巴嫩",
    country_code: "LB",
    label: "+961",
  },
  {
    name: "Saint Lucia",
    chinese_name: "圣露西亚",
    country_code: "LC",
    label: "+1758",
  },
  {
    name: "Liechtenstein",
    chinese_name: "列支敦士登",
    country_code: "LI",
    label: "+423",
  },
  {
    name: "Sri Lanka",
    chinese_name: "斯里兰卡",
    country_code: "LK",
    label: "+94",
  },
  {
    name: "Liberia",
    chinese_name: "利比里亚",
    country_code: "LR",
    label: "+231",
  },
  {
    name: "Lesotho",
    chinese_name: "莱索托",
    country_code: "LS",
    label: "+266",
  },
  {
    name: "Lithuania",
    chinese_name: "立陶宛",
    country_code: "LT",
    label: "+370",
  },
  {
    name: "Luxembourg",
    chinese_name: "卢森堡",
    country_code: "LU",
    label: "+352",
  },
  {
    name: "Latvia",
    chinese_name: "拉脱维亚",
    country_code: "LV",
    label: "+371",
  },
  {
    name: "Libya",
    chinese_name: "利比亚",
    country_code: "LY",
    label: "+218",
  },
  {
    name: "Morocco",
    chinese_name: "摩洛哥",
    country_code: "MA",
    label: "+212",
  },
  {
    name: "Monaco",
    chinese_name: "摩纳哥",
    country_code: "MC",
    label: "+377",
  },
  {
    name: "Moldova",
    chinese_name: "摩尔多瓦",
    country_code: "MD",
    label: "+373",
  },
  {
    name: "Montenegro",
    chinese_name: "黑山",
    country_code: "ME",
    label: "+382",
  },
  {
    name: "Madagascar",
    chinese_name: "马达加斯加",
    country_code: "MG",
    label: "+261",
  },
  {
    name: "Marshall Islands",
    chinese_name: "马绍尔群岛",
    country_code: "MH",
    label: "+692",
  },
  {
    name: "Macedonia",
    chinese_name: "马其顿",
    country_code: "MK",
    label: "+389",
  },
  {
    name: "Mali",
    chinese_name: "马里",
    country_code: "ML",
    label: "+223",
  },
  {
    name: "Myanmar",
    chinese_name: "缅甸",
    country_code: "MM",
    label: "+95",
  },
  {
    name: "Mongolia",
    chinese_name: "蒙古",
    country_code: "MN",
    label: "+976",
  },
  {
    name: "Macau",
    chinese_name: "中国澳门",
    country_code: "MO",
    label: "+853",
  },
  {
    name: "Mauritania",
    chinese_name: "毛里塔尼亚",
    country_code: "MR",
    label: "+222",
  },
  {
    name: "Montserrat",
    chinese_name: "蒙特塞拉特岛",
    country_code: "MS",
    label: "+1664",
  },
  {
    name: "Malta",
    chinese_name: "马耳他",
    country_code: "MT",
    label: "+356",
  },
  {
    name: "Mauritius",
    chinese_name: "毛里求斯",
    country_code: "MU",
    label: "+230",
  },
  {
    name: "Maldives",
    chinese_name: "马尔代夫",
    country_code: "MV",
    label: "+960",
  },
  {
    name: "Malawi",
    chinese_name: "马拉维",
    country_code: "MW",
    label: "+265",
  },
  {
    name: "Mexico",
    chinese_name: "墨西哥",
    country_code: "MX",
    label: "+52",
  },
  {
    name: "Malaysia",
    chinese_name: "马来西亚",
    country_code: "MY",
    label: "+60",
  },
  {
    name: "Mozambique",
    chinese_name: "莫桑比克",
    country_code: "MZ",
    label: "+258",
  },
  {
    name: "Namibia",
    chinese_name: "纳米比亚",
    country_code: "NA",
    label: "+264",
  },
  {
    name: "New Caledonia",
    chinese_name: "新喀里多尼亚",
    country_code: "NC",
    label: "+687",
  },
  {
    name: "Niger",
    chinese_name: "尼日尔",
    country_code: "NE",
    label: "+227",
  },
  {
    name: "Nigeria",
    chinese_name: "尼日利亚",
    country_code: "NG",
    label: "+234",
  },
  {
    name: "Nicaragua",
    chinese_name: "尼加拉瓜",
    country_code: "NI",
    label: "+505",
  },
  {
    name: "Netherlands",
    chinese_name: "荷兰",
    country_code: "NL",
    label: "+31",
  },
  {
    name: "Norway",
    chinese_name: "挪威",
    country_code: "NO",
    label: "+47",
  },
  {
    name: "Nepal",
    chinese_name: "尼泊尔",
    country_code: "NP",
    label: "+977",
  },
  {
    name: "Nauru",
    chinese_name: "拿鲁岛",
    country_code: "NR",
    label: "+674",
  },
  {
    name: "New Zealand",
    chinese_name: "新西兰",
    country_code: "NZ",
    label: "+64",
  },
  {
    name: "Oman",
    chinese_name: "阿曼",
    country_code: "OM",
    label: "+968",
  },
  {
    name: "Panama",
    chinese_name: "巴拿马",
    country_code: "PA",
    label: "+507",
  },
  {
    name: "Peru",
    chinese_name: "秘鲁",
    country_code: "PE",
    label: "+51",
  },
  {
    name: "French Polynesia",
    chinese_name: "法属波利尼西亚",
    country_code: "PF",
    label: "+689",
  },
  {
    name: "Papua New Guinea",
    chinese_name: "巴布亚新几内亚",
    country_code: "PG",
    label: "+675",
  },
  {
    name: "Philippines",
    chinese_name: "菲律宾",
    country_code: "PH",
    label: "+63",
  },
  {
    name: "Pakistan",
    chinese_name: "巴基斯坦",
    country_code: "PK",
    label: "+92",
  },
  {
    name: "Poland",
    chinese_name: "波兰",
    country_code: "PL",
    label: "+48",
  },
  {
    name: "Saint Pierreand Miquelon",
    chinese_name: "圣彼埃尔和密克隆岛",
    country_code: "PM",
    label: "+508",
  },
  {
    name: "Puerto Rico",
    chinese_name: "波多黎各",
    country_code: "PR",
    label: "+1787",
  },
  {
    name: "Portugal",
    chinese_name: "葡萄牙",
    country_code: "PT",
    label: "+351",
  },
  {
    name: "Palau",
    chinese_name: "帕劳",
    country_code: "PW",
    label: "+680",
  },
  {
    name: "Paraguay",
    chinese_name: "巴拉圭",
    country_code: "PY",
    label: "+595",
  },
  {
    name: "Qatar",
    chinese_name: "卡塔尔",
    country_code: "QA",
    label: "+974",
  },
  {
    name: "Réunion Island",
    chinese_name: "留尼汪",
    country_code: "RE",
    label: "+262",
  },
  {
    name: "Romania",
    chinese_name: "罗马尼亚",
    country_code: "RO",
    label: "+40",
  },
  {
    name: "Serbia",
    chinese_name: "塞尔维亚",
    country_code: "RS",
    label: "+381",
  },
  {
    name: "Russia",
    chinese_name: "俄罗斯",
    country_code: "RU",
    label: "+7",
  },
  {
    name: "Rwanda",
    chinese_name: "卢旺达",
    country_code: "RW",
    label: "+250",
  },
  {
    name: "Saudi Arabia",
    chinese_name: "沙特阿拉伯",
    country_code: "SA",
    label: "+966",
  },
  {
    name: "Solomon Islands",
    chinese_name: "所罗门群岛",
    country_code: "SB",
    label: "+677",
  },
  {
    name: "Seychelles",
    chinese_name: "塞舌尔",
    country_code: "SC",
    label: "+248",
  },
  {
    name: "Sudan",
    chinese_name: "苏丹",
    country_code: "SD",
    label: "+249",
  },
  {
    name: "Sweden",
    chinese_name: "瑞典",
    country_code: "SE",
    label: "+46",
  },
  {
    name: "Singapore",
    chinese_name: "新加坡",
    country_code: "SG",
    label: "+65",
  },
  {
    name: "Slovenia",
    chinese_name: "斯洛文尼亚",
    country_code: "SI",
    label: "+386",
  },
  {
    name: "Slovakia",
    chinese_name: "斯洛伐克",
    country_code: "SK",
    label: "+421",
  },
  {
    name: "Sierra Leone",
    chinese_name: "塞拉利昂",
    country_code: "SL",
    label: "+232",
  },
  {
    name: "San Marino",
    chinese_name: "圣马力诺",
    country_code: "SM",
    label: "+378",
  },
  {
    name: "Senegal",
    chinese_name: "塞内加尔",
    country_code: "SN",
    label: "+221",
  },
  {
    name: "Somalia",
    chinese_name: "索马里",
    country_code: "SO",
    label: "+252",
  },
  {
    name: "Suriname",
    chinese_name: "苏里南",
    country_code: "SR",
    label: "+597",
  },
  {
    name: "Sao Tome and Principe",
    chinese_name: "圣多美和普林西比",
    country_code: "ST",
    label: "+239",
  },
  {
    name: "ElSalvador",
    chinese_name: "萨尔瓦多",
    country_code: "SV",
    label: "+503",
  },
  {
    name: "Syria",
    chinese_name: "叙利亚",
    country_code: "SY",
    label: "+963",
  },
  {
    name: "Swaziland",
    chinese_name: "斯威士兰",
    country_code: "SZ",
    label: "+268",
  },
  {
    name: "Turksand Caicos Islands",
    chinese_name: "特克斯和凯科斯群岛",
    country_code: "TC",
    label: "+1649",
  },
  {
    name: "Chad",
    chinese_name: "乍得",
    country_code: "TD",
    label: "+235",
  },
  {
    name: "Togo",
    chinese_name: "多哥",
    country_code: "TG",
    label: "+228",
  },
  {
    name: "Thailand",
    chinese_name: "泰国",
    country_code: "TH",
    label: "+66",
  },
  {
    name: "Tajikistan",
    chinese_name: "塔吉克斯坦",
    country_code: "TJ",
    label: "+992",
  },
  {
    name: "East Timor",
    chinese_name: "东帝汶",
    country_code: "TL",
    label: "+670",
  },
  {
    name: "Turkmenistan",
    chinese_name: "土库曼斯坦",
    country_code: "TM",
    label: "+993",
  },
  {
    name: "Tunisia",
    chinese_name: "突尼斯",
    country_code: "TN",
    label: "+216",
  },
  {
    name: "Tonga",
    chinese_name: "汤加",
    country_code: "TO",
    label: "+676",
  },
  {
    name: "Turkey",
    chinese_name: "土耳其",
    country_code: "TR",
    label: "+90",
  },
  {
    name: "Trinidadand Tobago",
    chinese_name: "特立尼达和多巴哥",
    country_code: "TT",
    label: "+1868",
  },
  {
    name: "Taiwan",
    chinese_name: "中国台湾",
    country_code: "TW",
    label: "+886",
  },
  {
    name: "Tanzania",
    chinese_name: "坦桑尼亚",
    country_code: "TZ",
    label: "+255",
  },
  {
    name: "Ukraine",
    chinese_name: "乌克兰",
    country_code: "UA",
    label: "+380",
  },
  {
    name: "Uganda",
    chinese_name: "乌干达",
    country_code: "UG",
    label: "+256",
  },
  {
    name: "United States",
    chinese_name: "美国",
    country_code: "US",
    label: "+1",
  },
  {
    name: "Uruguay",
    chinese_name: "乌拉圭",
    country_code: "UY",
    label: "+598",
  },
  {
    name: "Uzbekistan",
    chinese_name: "乌兹别克斯坦",
    country_code: "UZ",
    label: "+998",
  },
  {
    name: "Saint Vincent and The Grenadines",
    chinese_name: "圣文森特和格林纳丁斯",
    country_code: "VC",
    label: "+1784",
  },
  {
    name: "Venezuela",
    chinese_name: "委内瑞拉",
    country_code: "VE",
    label: "+58",
  },
  {
    name: "VirginIslands,British",
    chinese_name: "英属处女群岛",
    country_code: "VG",
    label: "+1284",
  },
  {
    name: "Vietnam",
    chinese_name: "越南",
    country_code: "VN",
    label: "+84",
  },
  {
    name: "Vanuatu",
    chinese_name: "瓦努阿图",
    country_code: "VU",
    label: "+678",
  },
  {
    name: "Samoa",
    chinese_name: "萨摩亚",
    country_code: "WS",
    label: "+685",
  },
  {
    name: "Yemen",
    chinese_name: "也门",
    country_code: "YE",
    label: "+967",
  },
  {
    name: "Mayotte",
    chinese_name: "马约特",
    country_code: "YT",
    label: "+269",
  },
  {
    name: "South Africa",
    chinese_name: "南非",
    country_code: "ZA",
    label: "+27",
  },
  {
    name: "Zambia",
    chinese_name: "赞比亚",
    country_code: "ZM",
    label: "+260",
  },
  {
    name: "Zimbabwe",
    chinese_name: "津巴布韦",
    country_code: "ZW",
    label: "+263",
  },
];
